[build]
  base = "Disaster Recovery Qld/Website" # only if the project is in a subdirectory
  publish = "out"
  command = "npm run build:static"

# Add environment variables if needed
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://your-api-url.com"
